version: 2
registries:
  npm-registry-agora-dequecloud-com-artifactory-api-npm-dequelabs:
    type: npm-registry
    url: https://agora.dequecloud.com/artifactory/api/npm/dequelabs/
    username: "${{secrets.NPM_REGISTRY_AGORA_DEQUECLOUD_COM_ARTIFACTORY_API_NPM_DEQUELABS_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_AGORA_DEQUECLOUD_COM_ARTIFACTORY_API_NPM_DEQUELABS_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.6
    - 3.12.7
    - 3.12.8
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: standard-version
    versions:
    - 9.1.0
    - 9.1.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  registries:
  - npm-registry-agora-dequecloud-com-artifactory-api-npm-dequelabs
